name: MEM0 CI Pipeline - Staging

on:
  push:
    branches:
      - staging
      - feature/**
      - ai-secret-manager-integrate

env:
  C_NAME: "ivy-mem0-staging"
  TR_ARN: "ecs-task-role-ivy-mem0-staging"
  ER_ARN: "ecs-task-execution-role-ivy-mem0-staging"
  AWS_LG: "/ecs/staging/ivy-mem0"
  AWS_SP: "mem0"
  T_FAMILY: "ivy-mem0-staging"
  ECR_REPOSITORY_NAME_BACKEND: "ivy-backend-staging"
  ECR_REPOSITORY_NAME_DASHBOARD: "ivy-frontend-staging"

jobs:
  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -al

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_STG }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag backend image
        run: |
          IMAGE_TAG="${{ github.sha }}"
          BACKEND_IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY_NAME_BACKEND:$IMAGE_TAG"

          docker build \
            -t $BACKEND_IMAGE_URI -f server/dev.Dockerfile .

          echo "BACKEND_IMAGE_URI=$BACKEND_IMAGE_URI" >> $GITHUB_ENV

      - name: Build and tag dashboard image
        run: |
          IMAGE_TAG="${{ github.sha }}"
          DASHBOARD_IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY_NAME_DASHBOARD:$IMAGE_TAG"

          docker build \
            --build-arg NEXT_BASE_PATH=/mem0 \
            -t $DASHBOARD_IMAGE_URI -f server/dashboard/Dockerfile server/dashboard

          echo "DASHBOARD_IMAGE_URI=$DASHBOARD_IMAGE_URI" >> $GITHUB_ENV

      - name: Push images to Amazon ECR
        run: |
          docker push ${{ env.BACKEND_IMAGE_URI }}
          docker push ${{ env.DASHBOARD_IMAGE_URI }}

      - name: Save Docker images as artifact
        run: |
          docker save -o ivy-mem0-images.tar ${{ env.BACKEND_IMAGE_URI }} ${{ env.DASHBOARD_IMAGE_URI }}

      - name: Upload Docker images artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: ivy-mem0-images.tar

    outputs:
      backend_image_uri: ${{ env.BACKEND_IMAGE_URI }}
      dashboard_image_uri: ${{ env.DASHBOARD_IMAGE_URI }}
